// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/agent.proto

package agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HealthCheckResponse_ServingStatus 健康状态枚举
type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN     HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING     HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_NOT_SERVING HealthCheckResponse_ServingStatus = 2
)

func (x HealthCheckResponse_ServingStatus) Enum() *HealthCheckResponse_ServingStatus {
	p := new(HealthCheckResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_proto_enumTypes[0].Descriptor()
}

func (HealthCheckResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_proto_agent_proto_enumTypes[0]
}

func (x HealthCheckResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// DiagnoseRequest 诊断请求
type DiagnoseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string            `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Query     string            `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Mode      string            `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	Context   map[string]string `protobuf:"bytes,4,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *DiagnoseRequest) Reset() {
	*x = DiagnoseRequest{}
}

func (x *DiagnoseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnoseRequest) ProtoMessage() {}

func (x *DiagnoseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DiagnoseRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DiagnoseRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *DiagnoseRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *DiagnoseRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

// DiagnoseResponse 诊断响应
type DiagnoseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success            bool                `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message            string              `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Intent             string              `protobuf:"bytes,3,opt,name=intent,proto3" json:"intent,omitempty"`
	Confidence         float32             `protobuf:"fixed32,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Trace              []*TraceStep        `protobuf:"bytes,5,rep,name=trace,proto3" json:"trace,omitempty"`
	ChartData          *ChartData          `protobuf:"bytes,6,opt,name=chart_data,json=chartData,proto3" json:"chart_data,omitempty"`
	SkillRecommendation *SkillRecommendation `protobuf:"bytes,7,opt,name=skill_recommendation,json=skillRecommendation,proto3" json:"skill_recommendation,omitempty"`
}

func (x *DiagnoseResponse) Reset() {
	*x = DiagnoseResponse{}
}

func (x *DiagnoseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnoseResponse) ProtoMessage() {}

func (x *DiagnoseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DiagnoseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DiagnoseResponse) GetIntent() string {
	if x != nil {
		return x.Intent
	}
	return ""
}

func (x *DiagnoseResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *DiagnoseResponse) GetTrace() []*TraceStep {
	if x != nil {
		return x.Trace
	}
	return nil
}

func (x *DiagnoseResponse) GetChartData() *ChartData {
	if x != nil {
		return x.ChartData
	}
	return nil
}

func (x *DiagnoseResponse) GetSkillRecommendation() *SkillRecommendation {
	if x != nil {
		return x.SkillRecommendation
	}
	return nil
}

// TraceStep 追踪步骤
type TraceStep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StepId     int32  `protobuf:"varint,1,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	StepType   string `protobuf:"bytes,2,opt,name=step_type,json=stepType,proto3" json:"step_type,omitempty"`
	AgentName  string `protobuf:"bytes,3,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	Action     string `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	Reasoning  string `protobuf:"bytes,5,opt,name=reasoning,proto3" json:"reasoning,omitempty"`
	DurationMs int32  `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Status     string `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *TraceStep) Reset() {
	*x = TraceStep{}
}

func (x *TraceStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceStep) ProtoMessage() {}

func (x *TraceStep) GetStepId() int32 {
	if x != nil {
		return x.StepId
	}
	return 0
}

func (x *TraceStep) GetStepType() string {
	if x != nil {
		return x.StepType
	}
	return ""
}

func (x *TraceStep) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *TraceStep) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *TraceStep) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

func (x *TraceStep) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *TraceStep) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// ChartData 图表数据
type ChartData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Base64      string `protobuf:"bytes,1,opt,name=base64,proto3" json:"base64,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ChartType   string `protobuf:"bytes,4,opt,name=chart_type,json=chartType,proto3" json:"chart_type,omitempty"`
}

func (x *ChartData) Reset() {
	*x = ChartData{}
}

func (x *ChartData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChartData) ProtoMessage() {}

func (x *ChartData) GetBase64() string {
	if x != nil {
		return x.Base64
	}
	return ""
}

func (x *ChartData) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ChartData) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ChartData) GetChartType() string {
	if x != nil {
		return x.ChartType
	}
	return ""
}

// SkillRecommendation Skill 推荐
type SkillRecommendation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Recommended          bool    `protobuf:"varint,1,opt,name=recommended,proto3" json:"recommended,omitempty"`
	Reason               string  `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	SuggestedName        string  `protobuf:"bytes,3,opt,name=suggested_name,json=suggestedName,proto3" json:"suggested_name,omitempty"`
	SuggestedDescription string  `protobuf:"bytes,4,opt,name=suggested_description,json=suggestedDescription,proto3" json:"suggested_description,omitempty"`
	Confidence           float32 `protobuf:"fixed32,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
}

func (x *SkillRecommendation) Reset() {
	*x = SkillRecommendation{}
}

func (x *SkillRecommendation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillRecommendation) ProtoMessage() {}

func (x *SkillRecommendation) GetRecommended() bool {
	if x != nil {
		return x.Recommended
	}
	return false
}

func (x *SkillRecommendation) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *SkillRecommendation) GetSuggestedName() string {
	if x != nil {
		return x.SuggestedName
	}
	return ""
}

func (x *SkillRecommendation) GetSuggestedDescription() string {
	if x != nil {
		return x.SuggestedDescription
	}
	return ""
}

func (x *SkillRecommendation) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

// SearchRequest 搜索请求
type SearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query      string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	TopK       int32    `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	Filters    []string `protobuf:"bytes,3,rep,name=filters,proto3" json:"filters,omitempty"`
	Collection string   `protobuf:"bytes,4,opt,name=collection,proto3" json:"collection,omitempty"`
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *SearchRequest) GetFilters() []string {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *SearchRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

// SearchResponse 搜索响应
type SearchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool            `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Results []*SearchResult `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	Total   int32           `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Error   string          `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// SearchResult 搜索结果
type SearchResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DocId      string            `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Content    string            `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Score      float32           `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"`
	Metadata   map[string]string `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ChunkIndex int32             `protobuf:"varint,5,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *SearchResult) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SearchResult) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SearchResult) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SearchResult) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

// VisualizeRequest 可视化请求
type VisualizeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query        string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	OutputFormat string `protobuf:"bytes,2,opt,name=output_format,json=outputFormat,proto3" json:"output_format,omitempty"`
	Width        int32  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height       int32  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *VisualizeRequest) Reset() {
	*x = VisualizeRequest{}
}

func (x *VisualizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisualizeRequest) ProtoMessage() {}

func (x *VisualizeRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *VisualizeRequest) GetOutputFormat() string {
	if x != nil {
		return x.OutputFormat
	}
	return ""
}

func (x *VisualizeRequest) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *VisualizeRequest) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

// VisualizeResponse 可视化响应
type VisualizeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success     bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ChartBase64 string `protobuf:"bytes,2,opt,name=chart_base64,json=chartBase64,proto3" json:"chart_base64,omitempty"`
	ChartHtml   string `protobuf:"bytes,3,opt,name=chart_html,json=chartHtml,proto3" json:"chart_html,omitempty"`
	Title       string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	ChartType   string `protobuf:"bytes,6,opt,name=chart_type,json=chartType,proto3" json:"chart_type,omitempty"`
	Error       string `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *VisualizeResponse) Reset() {
	*x = VisualizeResponse{}
}

func (x *VisualizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisualizeResponse) ProtoMessage() {}

func (x *VisualizeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *VisualizeResponse) GetChartBase64() string {
	if x != nil {
		return x.ChartBase64
	}
	return ""
}

func (x *VisualizeResponse) GetChartHtml() string {
	if x != nil {
		return x.ChartHtml
	}
	return ""
}

func (x *VisualizeResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VisualizeResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *VisualizeResponse) GetChartType() string {
	if x != nil {
		return x.ChartType
	}
	return ""
}

func (x *VisualizeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// HealthCheckRequest 健康检查请求
type HealthCheckRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Service string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

// HealthCheckResponse 健康检查响应
type HealthCheckResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status     HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=agent.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	Version    string                           `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Components map[string]string                `protobuf:"bytes,3,rep,name=components,proto3" json:"components,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetComponents() map[string]string {
	if x != nil {
		return x.Components
	}
	return nil
}

// DiagnoseChunk 流式诊断响应块
type DiagnoseChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StepName    string            `protobuf:"bytes,1,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`
	Status      string            `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message     string            `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	IsFinal     bool              `protobuf:"varint,4,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	FinalResult *DiagnoseResponse `protobuf:"bytes,5,opt,name=final_result,json=finalResult,proto3" json:"final_result,omitempty"`
}

func (x *DiagnoseChunk) Reset() {
	*x = DiagnoseChunk{}
}

func (x *DiagnoseChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnoseChunk) ProtoMessage() {}

func (x *DiagnoseChunk) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *DiagnoseChunk) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DiagnoseChunk) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DiagnoseChunk) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *DiagnoseChunk) GetFinalResult() *DiagnoseResponse {
	if x != nil {
		return x.FinalResult
	}
	return nil
}

// 辅助类型定义
type DiagnoseRequest_ContextEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

type SearchResult_MetadataEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

type HealthCheckResponse_ComponentsEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

var File_proto_agent_proto protoreflect.FileDescriptor

var file_proto_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_agent_proto_goTypes = []interface{}{
	(HealthCheckResponse_ServingStatus)(0), // 0: agent.HealthCheckResponse.ServingStatus
	(*DiagnoseRequest)(nil),                // 1: agent.DiagnoseRequest
	(*DiagnoseResponse)(nil),               // 2: agent.DiagnoseResponse
	(*TraceStep)(nil),                      // 3: agent.TraceStep
	(*ChartData)(nil),                      // 4: agent.ChartData
	(*SkillRecommendation)(nil),            // 5: agent.SkillRecommendation
	(*SearchRequest)(nil),                  // 6: agent.SearchRequest
	(*SearchResponse)(nil),                 // 7: agent.SearchResponse
	(*SearchResult)(nil),                   // 8: agent.SearchResult
	(*VisualizeRequest)(nil),               // 9: agent.VisualizeRequest
	(*VisualizeResponse)(nil),              // 10: agent.VisualizeResponse
	(*HealthCheckRequest)(nil),             // 11: agent.HealthCheckRequest
	(*HealthCheckResponse)(nil),            // 12: agent.HealthCheckResponse
	(*DiagnoseChunk)(nil),                  // 13: agent.DiagnoseChunk
	nil,                                    // 14: agent.DiagnoseRequest.ContextEntry
	nil,                                    // 15: agent.SearchResult.MetadataEntry
	nil,                                    // 16: agent.HealthCheckResponse.ComponentsEntry
}
var file_proto_agent_proto_depIdxs = []int32{
	3,  // 0: agent.DiagnoseResponse.trace:type_name -> agent.TraceStep
	4,  // 1: agent.DiagnoseResponse.chart_data:type_name -> agent.ChartData
	5,  // 2: agent.DiagnoseResponse.skill_recommendation:type_name -> agent.SkillRecommendation
	14, // 3: agent.DiagnoseRequest.context:type_name -> agent.DiagnoseRequest.ContextEntry
	8,  // 4: agent.SearchResponse.results:type_name -> agent.SearchResult
	15, // 5: agent.SearchResult.metadata:type_name -> agent.SearchResult.MetadataEntry
	0,  // 6: agent.HealthCheckResponse.status:type_name -> agent.HealthCheckResponse.ServingStatus
	16, // 7: agent.HealthCheckResponse.components:type_name -> agent.HealthCheckResponse.ComponentsEntry
	2,  // 8: agent.DiagnoseChunk.final_result:type_name -> agent.DiagnoseResponse
}

func init() { file_proto_agent_proto_init() }
func file_proto_agent_proto_init() {
	// 初始化代码...
}
