// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: proto/agent.proto

package agent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

const (
	AgentService_Diagnose_FullMethodName       = "/agent.AgentService/Diagnose"
	AgentService_SearchKnowledge_FullMethodName = "/agent.AgentService/SearchKnowledge"
	AgentService_Visualize_FullMethodName      = "/agent.AgentService/Visualize"
	AgentService_DiagnoseStream_FullMethodName = "/agent.AgentService/DiagnoseStream"
	AgentService_HealthCheck_FullMethodName    = "/agent.AgentService/HealthCheck"
)

// AgentServiceClient is the client API for AgentService service.
type AgentServiceClient interface {
	Diagnose(ctx context.Context, in *DiagnoseRequest, opts ...grpc.CallOption) (*DiagnoseResponse, error)
	SearchKnowledge(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	Visualize(ctx context.Context, in *VisualizeRequest, opts ...grpc.CallOption) (*VisualizeResponse, error)
	DiagnoseStream(ctx context.Context, in *DiagnoseRequest, opts ...grpc.CallOption) (AgentService_DiagnoseStreamClient, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) Diagnose(ctx context.Context, in *DiagnoseRequest, opts ...grpc.CallOption) (*DiagnoseResponse, error) {
	out := new(DiagnoseResponse)
	err := c.cc.Invoke(ctx, AgentService_Diagnose_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) SearchKnowledge(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, AgentService_SearchKnowledge_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Visualize(ctx context.Context, in *VisualizeRequest, opts ...grpc.CallOption) (*VisualizeResponse, error) {
	out := new(VisualizeResponse)
	err := c.cc.Invoke(ctx, AgentService_Visualize_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) DiagnoseStream(ctx context.Context, in *DiagnoseRequest, opts ...grpc.CallOption) (AgentService_DiagnoseStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_DiagnoseStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &agentServiceDiagnoseStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AgentService_DiagnoseStreamClient interface {
	Recv() (*DiagnoseChunk, error)
	grpc.ClientStream
}

type agentServiceDiagnoseStreamClient struct {
	grpc.ClientStream
}

func (x *agentServiceDiagnoseStreamClient) Recv() (*DiagnoseChunk, error) {
	m := new(DiagnoseChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *agentServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, AgentService_HealthCheck_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
type AgentServiceServer interface {
	Diagnose(context.Context, *DiagnoseRequest) (*DiagnoseResponse, error)
	SearchKnowledge(context.Context, *SearchRequest) (*SearchResponse, error)
	Visualize(context.Context, *VisualizeRequest) (*VisualizeResponse, error)
	DiagnoseStream(*DiagnoseRequest, AgentService_DiagnoseStreamServer) error
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
}

// UnimplementedAgentServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAgentServiceServer struct {
}

func (UnimplementedAgentServiceServer) Diagnose(context.Context, *DiagnoseRequest) (*DiagnoseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Diagnose not implemented")
}
func (UnimplementedAgentServiceServer) SearchKnowledge(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchKnowledge not implemented")
}
func (UnimplementedAgentServiceServer) Visualize(context.Context, *VisualizeRequest) (*VisualizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Visualize not implemented")
}
func (UnimplementedAgentServiceServer) DiagnoseStream(*DiagnoseRequest, AgentService_DiagnoseStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method DiagnoseStream not implemented")
}
func (UnimplementedAgentServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_Diagnose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiagnoseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Diagnose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Diagnose_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Diagnose(ctx, req.(*DiagnoseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_SearchKnowledge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).SearchKnowledge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_SearchKnowledge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).SearchKnowledge(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Visualize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VisualizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Visualize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Visualize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Visualize(ctx, req.(*VisualizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_DiagnoseStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DiagnoseRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).DiagnoseStream(m, &agentServiceDiagnoseStreamServer{stream})
}

type AgentService_DiagnoseStreamServer interface {
	Send(*DiagnoseChunk) error
	grpc.ServerStream
}

type agentServiceDiagnoseStreamServer struct {
	grpc.ServerStream
}

func (x *agentServiceDiagnoseStreamServer) Send(m *DiagnoseChunk) error {
	return x.ServerStream.SendMsg(m)
}

func _AgentService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Diagnose",
			Handler:    _AgentService_Diagnose_Handler,
		},
		{
			MethodName: "SearchKnowledge",
			Handler:    _AgentService_SearchKnowledge_Handler,
		},
		{
			MethodName: "Visualize",
			Handler:    _AgentService_Visualize_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _AgentService_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DiagnoseStream",
			Handler:       _AgentService_DiagnoseStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/agent.proto",
}
