// Code generated by hertztool.

package main

import (
	"context"

	"code.byted.org/gopkg/env"
	"code.byted.org/gopkg/logs"
	"code.byted.org/gopkg/tccclient"
	"code.byted.org/middleware/hertz/byted"
	"code.byted.org/oec/lazyman/metricsutil"
	_ "code.byted.org/oec/oncall_opinion_analyse/biz/util/common"
	jsoniter "github.com/json-iterator/go"
)

type SwitchConfig struct {
	DefaultSwitchPercent int32            `json:"default_switch_percent"`
	PsmConfig            map[string]int32 `json:"psm_config"`
}

func main() {
	byted.Init()
	r := byted.Default()
	// query.Init()
	// common.HttpClientInit()
	metricsutil.InitMetrics(env.PSM())

	tConf := tccclient.NewConfigV2()
	tConf.Confspace = "default"
	tc, err := tccclient.NewClientV2("oec_rc.asgw.conf", tConf)
	if err != nil {
		logs.Error("[SessionWare]init tcc client err: %+v", err)
	}
	switchConfig := &SwitchConfig{
		DefaultSwitchPercent: 0,
		PsmConfig:            map[string]int32{},
	}
	loadFunc := func() {
		if confStr, err := tc.Get(context.Background(), "session_ware_switch_config"); err == nil {
			conf := &SwitchConfig{}
			logs.Info("[SessionWare]get tcc config: %v", confStr)
			if err := jsoniter.UnmarshalFromString(confStr, switchConfig); err == nil {
				println(conf)
			} else {
				logs.Error("[SessionWare]unmarshal config err: %+v", err)
			}

		} else {
			logs.Error("[SessionWare]get tcc config err: %+v", err)
		}
	}
	loadFunc()

	register(r)
	r.Spin()
}
