// Code generated by hertztool
package main

import (
	"context"

	"code.byted.org/gopkg/logs/v2/log"
	"code.byted.org/middleware/hertz/pkg/app"
	"code.byted.org/middleware/hertz/pkg/app/server"
	"code.byted.org/oec/oncall_opinion_analyse/biz/handler"
	// "code.byted.org/oec/oncall_opinion_analyse/biz/handler"
)

// customizeRegister register customize routers.
func customizeRegister(r *server.Hertz) {
	// your code ...
	r.Any("/*action", func(c context.Context, ctx *app.RequestContext) {
		headers := make(map[string][]string)
		ctx.VisitAllHeaders(func(key, value []byte) {
			if _, e := headers[string(key)]; e {
				headers[string(key)] = append(headers[string(key)], string(value))
			} else {
				headers[string(key)] = []string{string(value)}
			}
		})
		log.V2.Info().With(c).Str("GetOncallCallback req headers:").Obj(headers).Emit()
	})
	r.GET("/oncall2/api/v1/test1", handler.TestBack1)
	r.GET("/oncall2/api/v1/test4", handler.TestBack4)
	r.GET("/oncall2/api/v1/test5", handler.TestBack5)
	r.GET("/osgw_v2/new/dispose/rd1", handler.DisposeTest1)
	r.GET("/osgw_v2/new/dispose/rd2", handler.DisposeTest2)
	r.GET("/osgw_v2/new/dispose/rd3", handler.DisposeTest3)
	r.GET("/osgw_v2/new/dispose/rd4", handler.DisposeStress)
	r.GET("/osgw_v2/test_captcha", handler.DisposeTest4)
	r.GET("/osgw_v2/new/dispose/qa1", handler.DisposeTest5)
	r.GET("/osgw_v2/new/dispose/qa2", handler.DisposeTest6)
	r.GET("/osgw_v2/new/dispose/qa3", handler.DisposeTest7)
	r.GET("/osgw_v2/new/dispose/qa4", handler.DisposeTest8)
	r.Any("/osgw_v2/new/dispose/qa5", handler.DisposeTest8)
	r.Any("/osgw_v2/new/dispose/qa6", handler.DisposeTest7)
	r.Any("/osgw_v2/new/dispose/qa7", handler.DisposeTest8)
	r.Any("/osgw_v2/new/dispose/qa8", handler.DisposeTest7)
	r.Any("/osgw_v2/new/dispose/qa9", handler.DisposeTest8)
	r.Any("/osgw_v2/new/dispose/qa10", handler.DisposeTest7)
	r.GET("/oncall2/api/v1/dispose/test9", handler.DisposeTest9)
	r.GET("/oncall2/api/v1/dispose/test10", handler.DisposeTest10)

	r.GET("/osgw_v2/oldixnew/exact/case/t1", handler.TestBack11)

	r.GET("/osgw_v2/resp1", handler.TestBack16)
	r.GET("/osgw_v2/resp2", handler.TestBack15)
	r.GET("/osgw_v2/resp3", handler.TestBack14)
	r.GET("/osgw_v2/resp4", handler.TestBack13)
	r.GET("/osgw_v2/resp5", handler.TestBack12)

	r.POST("/osgw_v2/new/dispose/rd1", handler.DisposeTest1)
	r.POST("/osgw_v2/new/dispose/rd2", handler.DisposeTest2)
	r.POST("/osgw_v2/new/dispose/rd3", handler.DisposeTest3)
	r.POST("/osgw_v2/test_captcha", handler.DisposeTest4)
	r.POST("/osgw_v2/new/dispose/qa1", handler.DisposeTest5)
	r.POST("/osgw_v2/new/dispose/qa2", handler.DisposeTest6)
	r.POST("/osgw_v2/new/dispose/qa3", handler.DisposeTest7)
	r.POST("/osgw_v2/new/dispose/qa4", handler.DisposeTest8)
	r.POST("/oncall2/api/v1/dispose/test9", handler.DisposeTest9)
	r.POST("/oncall2/api/v1/dispose/test10", handler.DisposeTest10)

	r.POST("/testserver3/dispose/test1", handler.DisposeTest1)

	r.GET("/oncall2/api/v1/dispose/color/test1", handler.DisposeColorTest1)
	r.GET("/oncall2/api/v1/dispose/color/test2", handler.DisposeColorTest2)
	r.GET("/oncall2/api/v1/dispose/color/test3", handler.DisposeColorTest3)

	r.GET("/oncall2/api/v1/dispose/tuomin/test1", handler.DisposeTuoMinTest1)
	r.GET("/oncall2/api/v1/dispose/tuomin/test2", handler.DisposeTuoMinTest2)
	r.GET("/oncall2/api/v1/dispose/tuomin/test3", handler.DisposeTuoMinTest3)

	r.GET("/oncall2/api/v1/dispose/poison/test1", handler.DisposePoisonTest1)
	r.GET("/oncall2/api/v1/dispose/poison/test2", handler.DisposePoisonTest2)
	r.GET("/oncall2/api/v1/dispose/poison/test3", handler.DisposePoisonTest3)

	r.GET("/osgw1/regex/v:version/", handler.DisposeStress1)
	r.GET("/osgw1/regex2/v:version/", handler.DisposeStress2)
	r.GET("/osgw1/regex3/v:version/", handler.DisposeStress3)
	r.GET("/osgw1/regex/api/v:version", handler.DisposeStress4)
	r.GET("/osgw1/exact/case/t1", handler.DisposeStress5)
	r.GET("/osgw1/exact/user/", handler.DisposeStress5)
	r.GET("/osgw1/prefix/prod:version", handler.DisposeStress7)
	r.GET("/osgw1/prefix/order/:version", handler.DisposeStress8)
	r.GET("/osgw1/regex/tts/open/:version", handler.DisposeStress9)
	r.GET("/osgw1/regex/full:version", handler.DisposeStress10)
	// r.GET("/osgw1/regex2/tts/open/:version", handler.DisposeStress11)
	// r.GET("/osgw1/regex3/tts/open/:version", handler.DisposeStress12)
	// r.GET("/osgw1/regex4/tts/open/:version", handler.DisposeStress13)

	r.GET("/osgw1/regex2/tts/open/:version", handler.DisposeStress20)
	r.GET("/osgw1/regex3/tts/open/:version", handler.DisposeStress20)
	r.GET("/osgw1/regex4/tts/open/:version", handler.DisposeStress20)
	r.GET("/osgw1/regex5/tts/open/:version", handler.DisposeStress23)
	r.GET("/osgw1/regex7/tts/open/:version", handler.DisposeStress24)
	r.GET("/osgw1/regex8/tts/open/:version", handler.DisposeStress25)
	r.GET("/osgw1/regex9/tts/open/:version", handler.DisposeStress25)
	r.GET("/osgw1/regex10/tts/open/:version", handler.DisposeStress25)
	r.GET("/osgw1/regex11/tts/open/:version", handler.DisposeStress25)

	r.POST("/osgw1/regex/v:version/", handler.DisposeStress1)
	r.POST("/osgw1/regex2/v:version/", handler.DisposeStress2)
	r.POST("/osgw1/regex3/v:version/", handler.DisposeStress3)
	r.POST("/osgw1/regex/api/v:version", handler.DisposeStress4)
	r.POST("/osgw1/exact/case/t1", handler.DisposeStress5)
	r.POST("/osgw1/exact/user/", handler.DisposeStress5)
	r.POST("/osgw1/prefix/prod:version", handler.DisposeStress7)
	r.POST("/osgw1/prefix/order/:version", handler.DisposeStress8)
	r.POST("/osgw1/regex/tts/open/:version", handler.DisposeStress9)
	r.POST("/osgw1/regex/full:version", handler.DisposeStress10)
	// r.POST("/osgw1/regex2/tts/open/:version", handler.DisposeStress11)
	// r.POST("/osgw1/regex3/tts/open/:version", handler.DisposeStress12)
	// r.POST("/osgw1/regex4/tts/open/:version", handler.DisposeStress13)

	r.POST("/osgw1/regex2/tts/open/:version", handler.DisposeStress20)
	r.POST("/osgw1/regex3/tts/open/:version", handler.DisposeStress20)
	r.POST("/osgw1/regex4/tts/open/:version", handler.DisposeStress20)
	r.POST("/osgw1/regex5/tts/open/:version", handler.DisposeStress23)
	r.POST("/osgw1/regex7/tts/open/:version", handler.DisposeStress24)
	r.POST("/osgw1/regex8/tts/open/:version", handler.DisposeStress25)
	r.POST("/osgw1/regex9/tts/open/:version", handler.DisposeStress25)
	r.POST("/osgw1/regex10/tts/open/:version", handler.DisposeStress25)
	r.POST("/osgw1/regex11/tts/open/:version", handler.DisposeStress25)

	r.GET("/oncall2/shasha/dispose/test1", handler.DisposeStress25)
	r.GET("/oncall2/shasha/dispose/test2", handler.DisposeStress25)
	r.GET("/oncall2/shasha/dispose/test3", handler.DisposeStress25)
	r.GET("/oncall2/shasha/dispose/test4", handler.DisposeStress25)
	r.GET("/oncall2/shasha/dispose/test5", handler.DisposeStress25)
	r.GET("/oncall2/shasha/dispose/test6", handler.DisposeStress25)
	r.GET("/oncall2/shasha/dispose/test7", handler.DisposeStress25)
	r.GET("/oncall2/shasha/dispose/test8", handler.DisposeStress25)
	r.GET("/oncall2/shasha/dispose/test9", handler.DisposeStress25)
	r.GET("/oncall2/shasha/dispose/test10", handler.DisposeStress25)

	r.POST("/oncall2/shasha/dispose/test1", handler.DisposeStress25)
	r.POST("/oncall2/shasha/dispose/test2", handler.DisposeStress25)
	r.POST("/oncall2/shasha/dispose/test3", handler.DisposeStress25)
	r.POST("/oncall2/shasha/dispose/test4", handler.DisposeStress25)
	r.POST("/oncall2/shasha/dispose/test5", handler.DisposeStress25)
	r.POST("/oncall2/shasha/dispose/test6", handler.DisposeStress25)
	r.POST("/oncall2/shasha/dispose/test7", handler.DisposeStress25)
	r.POST("/oncall2/shasha/dispose/test8", handler.DisposeStress25)
	r.POST("/oncall2/shasha/dispose/test9", handler.DisposeStress25)
	r.POST("/oncall2/shasha/dispose/test10", handler.DisposeStress25)

	r.Any("/osgw_v2/regex2/tts/open", handler.DisposeStress)
	r.Any("/osgw_v2/regex3/tts/open", handler.DisposeStress)
	r.Any("/osgw_v2/regex4/tts/open", handler.DisposeStress)
	r.Any("/osgw_v2/regex5/tts/open", handler.DisposeStress101)
	r.Any("/osgw_v2/regex7/tts/open", handler.DisposeStress102)
	r.Any("/osgw_v2/regex8/tts/open", handler.DisposeStress103)
	r.Any("/osgw_v2/regex9/tts/open", handler.DisposeStress103)
	r.Any("/osgw_v2/regex10/tts/open", handler.DisposeStress103)
	r.Any("/osgw_v2/regex11/tts/open", handler.DisposeStress103)

	r.Any("/osgw_v2/poison1", handler.DisposeStress)
	r.Any("/osgw_v2/poison2", handler.DisposeStress)
	r.Any("/osgw_v2/poison3", handler.DisposeStress)
	r.Any("/osgw_v2/poison4", handler.DisposeStress)
	r.Any("/osgw_v2/poison5", handler.DisposeStress)
	r.Any("/poison6", handler.DisposeStress)
	r.Any("/poison7", handler.DisposeStress)
}

func _api_mws() []app.HandlerFunc {
	return nil
}

func _api_v_version_mws() []app.HandlerFunc {
	return nil
}

func _api_v_version_oec_mws() []app.HandlerFunc {
	return nil
}

func _api_v_version_oec_oncall_mws() []app.HandlerFunc {
	return nil
}

func _api_v_version_oec_oncall_workorder_mws() []app.HandlerFunc {
	return nil
}

func _GetOncallCallback_mws() []app.HandlerFunc {
	return nil
}

func _api_v_version_oec_governance_mws() []app.HandlerFunc {
	return nil
}

func _api_v_version_oec_governance_qa_mws() []app.HandlerFunc {
	return nil
}

func _api_v_version_oec_governance_qa_argos_mws() []app.HandlerFunc {
	return nil
}

func _GetOncallArgosDIYCardCallback_mws() []app.HandlerFunc {
	return nil
}

func _IDVMock_mws() []app.HandlerFunc {
	return nil
}

func _osgw_v2_mws() []app.HandlerFunc {
	return nil
}

func _osgw_v2_mock_mws() []app.HandlerFunc {
	return nil
}

func _osgw_v2_autotest_mws() []app.HandlerFunc {
	return nil
}

func _AutoTestIdv_mws() []app.HandlerFunc {
	return nil
}
