// Code generated by hertztool

package main

import (
	"code.byted.org/middleware/hertz/pkg/app/server"
	"code.byted.org/oec/oncall_opinion_analyse/biz/handler"
)

// register register routes based on the IDL 'api.${HTTP Method}' annotation.
func register(r *server.Hertz) {
	//INSERT POINT: DO NOT CHANGE NEXT LINE!
	customizeRegister(r)

	r.GET("/ping", handler.Ping)
	{
		_api := r.Group("/api", _api_mws()...)
		{
			_v_version := _api.Group("/v:version", _api_v_version_mws()...)
			{
				_oec := _v_version.Group("/oec", _api_v_version_oec_mws()...)
				{
					_governance := _oec.Group("/governance", _api_v_version_oec_governance_mws()...)
					{
						_qa := _governance.Group("/qa", _api_v_version_oec_governance_qa_mws()...)
						{
							_argos := _qa.Group("/argos", _api_v_version_oec_governance_qa_argos_mws()...)
							_argos.POST("/callback", append(_GetOncallArgosDIYCardCallback_mws(), handler.GetOncallArgosDIYCardCallback)...)
						}
					}
				}
				{
					_oncall := _oec.Group("/oncall", _api_v_version_oec_oncall_mws()...)
					{
						_workorder := _oncall.Group("/workorder", _api_v_version_oec_oncall_workorder_mws()...)
						_workorder.POST("/callback", append(_GetOncallCallback_mws(), handler.GetOncallCallback)...)
					}
				}
			}
		}
	}
	{
		_osgw_v2 := r.Group("/osgw_v2", _osgw_v2_mws()...)
		{
			_autotest := _osgw_v2.Group("/autotest", _osgw_v2_autotest_mws()...)
			_autotest.Any("/idv", append(_AutoTestIdv_mws(), handler.AutoTestIdv)...)
		}
		{
			_mock := _osgw_v2.Group("/mock", _osgw_v2_mock_mws()...)
			_mock.Any("/idv", append(_IDVMock_mws(), handler.IDVMock)...)
		}
	}

	osgwApi := r.Group("/osgw_v4/api/osgw")
	wareAlarmConfigApi := osgwApi.Group("/wares_alarm")
	{
		wareAlarmConfigApi.POST("alarm_detail/callback", handler.HandleAlarmCallback)
	}
}
