// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"code.byted.org/oec/oncall_opinion_analyse/biz/dal/model"
)

func newAlertTask(db *gorm.DB) alertTask {
	_alertTask := alertTask{}

	_alertTask.alertTaskDo.UseDB(db)
	_alertTask.alertTaskDo.UseModel(&model.AlertTask{})

	tableName := _alertTask.alertTaskDo.TableName()
	_alertTask.ALL = field.NewAsterisk(tableName)
	_alertTask.ID = field.NewInt64(tableName, "id")
	_alertTask.OncallOriginID = field.NewInt64(tableName, "oncall_origin_id")
	_alertTask.TenantID = field.NewInt64(tableName, "tenant_id")
	_alertTask.AlterType = field.NewString(tableName, "alter_type")
	_alertTask.CTime = field.NewTime(tableName, "c_time")
	_alertTask.UTime = field.NewTime(tableName, "u_time")
	_alertTask.Level = field.NewString(tableName, "level")
	_alertTask.IsCallback = field.NewInt32(tableName, "is_callback")
	_alertTask.CrossOncallFlowID = field.NewInt64(tableName, "cross_oncall_flow_id")
	_alertTask.RootField = field.NewString(tableName, "root_field")

	_alertTask.fillFieldMap()

	return _alertTask
}

type alertTask struct {
	alertTaskDo alertTaskDo

	ALL               field.Asterisk
	ID                field.Int64  // 主键id
	OncallOriginID    field.Int64  // 原始oncall工单主键id
	TenantID          field.Int64  // 租户主键
	AlterType         field.String // 该条工单告警类别
	CTime             field.Time   // 落库时间
	UTime             field.Time   // 修改时间
	Level             field.String // 告警等级
	IsCallback        field.Int32  // 是否被argos告警callback过
	CrossOncallFlowID field.Int64  // 同流程内oncall工单关联id
	RootField         field.String // oncall id 租户所属业务域

	fieldMap map[string]field.Expr
}

func (a alertTask) Table(newTableName string) *alertTask {
	a.alertTaskDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a alertTask) As(alias string) *alertTask {
	a.alertTaskDo.DO = *(a.alertTaskDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *alertTask) updateTableName(table string) *alertTask {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt64(table, "id")
	a.OncallOriginID = field.NewInt64(table, "oncall_origin_id")
	a.TenantID = field.NewInt64(table, "tenant_id")
	a.AlterType = field.NewString(table, "alter_type")
	a.CTime = field.NewTime(table, "c_time")
	a.UTime = field.NewTime(table, "u_time")
	a.Level = field.NewString(table, "level")
	a.IsCallback = field.NewInt32(table, "is_callback")
	a.CrossOncallFlowID = field.NewInt64(table, "cross_oncall_flow_id")
	a.RootField = field.NewString(table, "root_field")

	a.fillFieldMap()

	return a
}

func (a *alertTask) WithContext(ctx context.Context) *alertTaskDo {
	return a.alertTaskDo.WithContext(ctx)
}

func (a alertTask) TableName() string { return a.alertTaskDo.TableName() }

func (a alertTask) Alias() string { return a.alertTaskDo.Alias() }

func (a *alertTask) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *alertTask) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 10)
	a.fieldMap["id"] = a.ID
	a.fieldMap["oncall_origin_id"] = a.OncallOriginID
	a.fieldMap["tenant_id"] = a.TenantID
	a.fieldMap["alter_type"] = a.AlterType
	a.fieldMap["c_time"] = a.CTime
	a.fieldMap["u_time"] = a.UTime
	a.fieldMap["level"] = a.Level
	a.fieldMap["is_callback"] = a.IsCallback
	a.fieldMap["cross_oncall_flow_id"] = a.CrossOncallFlowID
	a.fieldMap["root_field"] = a.RootField
}

func (a alertTask) clone(db *gorm.DB) alertTask {
	a.alertTaskDo.ReplaceDB(db)
	return a
}

type alertTaskDo struct{ gen.DO }

func (a alertTaskDo) Debug() *alertTaskDo {
	return a.withDO(a.DO.Debug())
}

func (a alertTaskDo) WithContext(ctx context.Context) *alertTaskDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a alertTaskDo) ReadDB() *alertTaskDo {
	return a.Clauses(dbresolver.Read)
}

func (a alertTaskDo) WriteDB() *alertTaskDo {
	return a.Clauses(dbresolver.Write)
}

func (a alertTaskDo) Clauses(conds ...clause.Expression) *alertTaskDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a alertTaskDo) Returning(value interface{}, columns ...string) *alertTaskDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a alertTaskDo) Not(conds ...gen.Condition) *alertTaskDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a alertTaskDo) Or(conds ...gen.Condition) *alertTaskDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a alertTaskDo) Select(conds ...field.Expr) *alertTaskDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a alertTaskDo) Where(conds ...gen.Condition) *alertTaskDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a alertTaskDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *alertTaskDo {
	return a.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (a alertTaskDo) Order(conds ...field.Expr) *alertTaskDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a alertTaskDo) Distinct(cols ...field.Expr) *alertTaskDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a alertTaskDo) Omit(cols ...field.Expr) *alertTaskDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a alertTaskDo) Join(table schema.Tabler, on ...field.Expr) *alertTaskDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a alertTaskDo) LeftJoin(table schema.Tabler, on ...field.Expr) *alertTaskDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a alertTaskDo) RightJoin(table schema.Tabler, on ...field.Expr) *alertTaskDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a alertTaskDo) Group(cols ...field.Expr) *alertTaskDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a alertTaskDo) Having(conds ...gen.Condition) *alertTaskDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a alertTaskDo) Limit(limit int) *alertTaskDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a alertTaskDo) Offset(offset int) *alertTaskDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a alertTaskDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *alertTaskDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a alertTaskDo) Unscoped() *alertTaskDo {
	return a.withDO(a.DO.Unscoped())
}

func (a alertTaskDo) Create(values ...*model.AlertTask) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a alertTaskDo) CreateInBatches(values []*model.AlertTask, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a alertTaskDo) Save(values ...*model.AlertTask) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a alertTaskDo) First() (*model.AlertTask, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertTask), nil
	}
}

func (a alertTaskDo) Take() (*model.AlertTask, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertTask), nil
	}
}

func (a alertTaskDo) Last() (*model.AlertTask, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertTask), nil
	}
}

func (a alertTaskDo) Find() ([]*model.AlertTask, error) {
	result, err := a.DO.Find()
	return result.([]*model.AlertTask), err
}

func (a alertTaskDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AlertTask, err error) {
	buf := make([]*model.AlertTask, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a alertTaskDo) FindInBatches(result *[]*model.AlertTask, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a alertTaskDo) Attrs(attrs ...field.AssignExpr) *alertTaskDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a alertTaskDo) Assign(attrs ...field.AssignExpr) *alertTaskDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a alertTaskDo) Joins(fields ...field.RelationField) *alertTaskDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a alertTaskDo) Preload(fields ...field.RelationField) *alertTaskDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a alertTaskDo) FirstOrInit() (*model.AlertTask, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertTask), nil
	}
}

func (a alertTaskDo) FirstOrCreate() (*model.AlertTask, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertTask), nil
	}
}

func (a alertTaskDo) FindByPage(offset int, limit int) (result []*model.AlertTask, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a alertTaskDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a alertTaskDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a alertTaskDo) Delete(models ...*model.AlertTask) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *alertTaskDo) withDO(do gen.Dao) *alertTaskDo {
	a.DO = *do.(*gen.DO)
	return a
}
