// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"code.byted.org/oec/oncall_opinion_analyse/biz/dal/model"
)

func newOncallListenAlertTask(db *gorm.DB) oncallListenAlertTask {
	_oncallListenAlertTask := oncallListenAlertTask{}

	_oncallListenAlertTask.oncallListenAlertTaskDo.UseDB(db)
	_oncallListenAlertTask.oncallListenAlertTaskDo.UseModel(&model.OncallListenAlertTask{})

	tableName := _oncallListenAlertTask.oncallListenAlertTaskDo.TableName()
	_oncallListenAlertTask.ALL = field.NewAsterisk(tableName)
	_oncallListenAlertTask.ID = field.NewInt64(tableName, "id")
	_oncallListenAlertTask.OncallOriginID = field.NewInt64(tableName, "oncall_origin_id")
	_oncallListenAlertTask.TenantID = field.NewInt64(tableName, "tenant_id")
	_oncallListenAlertTask.ActualAlertLevel = field.NewString(tableName, "actual_alert_level")
	_oncallListenAlertTask.CalculatedAlertLevel = field.NewString(tableName, "calculated_alert_level")
	_oncallListenAlertTask.MatchKeywords = field.NewString(tableName, "match_keywords")
	_oncallListenAlertTask.ClusterTags = field.NewString(tableName, "cluster_tags")
	_oncallListenAlertTask.Status = field.NewInt32(tableName, "status")
	_oncallListenAlertTask.CreateTime = field.NewString(tableName, "create_time")
	_oncallListenAlertTask.UpdateTime = field.NewString(tableName, "update_time")
	_oncallListenAlertTask.CTime = field.NewTime(tableName, "c_time")
	_oncallListenAlertTask.UTime = field.NewTime(tableName, "u_time")

	_oncallListenAlertTask.fillFieldMap()

	return _oncallListenAlertTask
}

type oncallListenAlertTask struct {
	oncallListenAlertTaskDo oncallListenAlertTaskDo

	ALL                  field.Asterisk
	ID                   field.Int64  // 主键id
	OncallOriginID       field.Int64  // 原始oncall工单主键id
	TenantID             field.Int64  // 租户主键
	ActualAlertLevel     field.String // 该条工单实际告警级别
	CalculatedAlertLevel field.String // 该条工单告警计算级别
	MatchKeywords        field.String // 工单命中关键词列表，包括匹配个数，目前默认为1个,ex:[{"kw1":1},...]
	ClusterTags          field.String // 工单聚合问题标签分类列表,ex:["tag1",...]
	Status               field.Int32  // 状态,0:初始化，1:工单告警处理中，99:工单结束
	CreateTime           field.String // 创建时间
	UpdateTime           field.String // 修改时间
	CTime                field.Time   // callback落库时间
	UTime                field.Time   // callback修改时间

	fieldMap map[string]field.Expr
}

func (o oncallListenAlertTask) Table(newTableName string) *oncallListenAlertTask {
	o.oncallListenAlertTaskDo.UseTable(newTableName)
	return o.updateTableName(newTableName)
}

func (o oncallListenAlertTask) As(alias string) *oncallListenAlertTask {
	o.oncallListenAlertTaskDo.DO = *(o.oncallListenAlertTaskDo.As(alias).(*gen.DO))
	return o.updateTableName(alias)
}

func (o *oncallListenAlertTask) updateTableName(table string) *oncallListenAlertTask {
	o.ALL = field.NewAsterisk(table)
	o.ID = field.NewInt64(table, "id")
	o.OncallOriginID = field.NewInt64(table, "oncall_origin_id")
	o.TenantID = field.NewInt64(table, "tenant_id")
	o.ActualAlertLevel = field.NewString(table, "actual_alert_level")
	o.CalculatedAlertLevel = field.NewString(table, "calculated_alert_level")
	o.MatchKeywords = field.NewString(table, "match_keywords")
	o.ClusterTags = field.NewString(table, "cluster_tags")
	o.Status = field.NewInt32(table, "status")
	o.CreateTime = field.NewString(table, "create_time")
	o.UpdateTime = field.NewString(table, "update_time")
	o.CTime = field.NewTime(table, "c_time")
	o.UTime = field.NewTime(table, "u_time")

	o.fillFieldMap()

	return o
}

func (o *oncallListenAlertTask) WithContext(ctx context.Context) *oncallListenAlertTaskDo {
	return o.oncallListenAlertTaskDo.WithContext(ctx)
}

func (o oncallListenAlertTask) TableName() string { return o.oncallListenAlertTaskDo.TableName() }

func (o oncallListenAlertTask) Alias() string { return o.oncallListenAlertTaskDo.Alias() }

func (o *oncallListenAlertTask) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := o.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (o *oncallListenAlertTask) fillFieldMap() {
	o.fieldMap = make(map[string]field.Expr, 12)
	o.fieldMap["id"] = o.ID
	o.fieldMap["oncall_origin_id"] = o.OncallOriginID
	o.fieldMap["tenant_id"] = o.TenantID
	o.fieldMap["actual_alert_level"] = o.ActualAlertLevel
	o.fieldMap["calculated_alert_level"] = o.CalculatedAlertLevel
	o.fieldMap["match_keywords"] = o.MatchKeywords
	o.fieldMap["cluster_tags"] = o.ClusterTags
	o.fieldMap["status"] = o.Status
	o.fieldMap["create_time"] = o.CreateTime
	o.fieldMap["update_time"] = o.UpdateTime
	o.fieldMap["c_time"] = o.CTime
	o.fieldMap["u_time"] = o.UTime
}

func (o oncallListenAlertTask) clone(db *gorm.DB) oncallListenAlertTask {
	o.oncallListenAlertTaskDo.ReplaceDB(db)
	return o
}

type oncallListenAlertTaskDo struct{ gen.DO }

func (o oncallListenAlertTaskDo) Debug() *oncallListenAlertTaskDo {
	return o.withDO(o.DO.Debug())
}

func (o oncallListenAlertTaskDo) WithContext(ctx context.Context) *oncallListenAlertTaskDo {
	return o.withDO(o.DO.WithContext(ctx))
}

func (o oncallListenAlertTaskDo) ReadDB() *oncallListenAlertTaskDo {
	return o.Clauses(dbresolver.Read)
}

func (o oncallListenAlertTaskDo) WriteDB() *oncallListenAlertTaskDo {
	return o.Clauses(dbresolver.Write)
}

func (o oncallListenAlertTaskDo) Clauses(conds ...clause.Expression) *oncallListenAlertTaskDo {
	return o.withDO(o.DO.Clauses(conds...))
}

func (o oncallListenAlertTaskDo) Returning(value interface{}, columns ...string) *oncallListenAlertTaskDo {
	return o.withDO(o.DO.Returning(value, columns...))
}

func (o oncallListenAlertTaskDo) Not(conds ...gen.Condition) *oncallListenAlertTaskDo {
	return o.withDO(o.DO.Not(conds...))
}

func (o oncallListenAlertTaskDo) Or(conds ...gen.Condition) *oncallListenAlertTaskDo {
	return o.withDO(o.DO.Or(conds...))
}

func (o oncallListenAlertTaskDo) Select(conds ...field.Expr) *oncallListenAlertTaskDo {
	return o.withDO(o.DO.Select(conds...))
}

func (o oncallListenAlertTaskDo) Where(conds ...gen.Condition) *oncallListenAlertTaskDo {
	return o.withDO(o.DO.Where(conds...))
}

func (o oncallListenAlertTaskDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *oncallListenAlertTaskDo {
	return o.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (o oncallListenAlertTaskDo) Order(conds ...field.Expr) *oncallListenAlertTaskDo {
	return o.withDO(o.DO.Order(conds...))
}

func (o oncallListenAlertTaskDo) Distinct(cols ...field.Expr) *oncallListenAlertTaskDo {
	return o.withDO(o.DO.Distinct(cols...))
}

func (o oncallListenAlertTaskDo) Omit(cols ...field.Expr) *oncallListenAlertTaskDo {
	return o.withDO(o.DO.Omit(cols...))
}

func (o oncallListenAlertTaskDo) Join(table schema.Tabler, on ...field.Expr) *oncallListenAlertTaskDo {
	return o.withDO(o.DO.Join(table, on...))
}

func (o oncallListenAlertTaskDo) LeftJoin(table schema.Tabler, on ...field.Expr) *oncallListenAlertTaskDo {
	return o.withDO(o.DO.LeftJoin(table, on...))
}

func (o oncallListenAlertTaskDo) RightJoin(table schema.Tabler, on ...field.Expr) *oncallListenAlertTaskDo {
	return o.withDO(o.DO.RightJoin(table, on...))
}

func (o oncallListenAlertTaskDo) Group(cols ...field.Expr) *oncallListenAlertTaskDo {
	return o.withDO(o.DO.Group(cols...))
}

func (o oncallListenAlertTaskDo) Having(conds ...gen.Condition) *oncallListenAlertTaskDo {
	return o.withDO(o.DO.Having(conds...))
}

func (o oncallListenAlertTaskDo) Limit(limit int) *oncallListenAlertTaskDo {
	return o.withDO(o.DO.Limit(limit))
}

func (o oncallListenAlertTaskDo) Offset(offset int) *oncallListenAlertTaskDo {
	return o.withDO(o.DO.Offset(offset))
}

func (o oncallListenAlertTaskDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *oncallListenAlertTaskDo {
	return o.withDO(o.DO.Scopes(funcs...))
}

func (o oncallListenAlertTaskDo) Unscoped() *oncallListenAlertTaskDo {
	return o.withDO(o.DO.Unscoped())
}

func (o oncallListenAlertTaskDo) Create(values ...*model.OncallListenAlertTask) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Create(values)
}

func (o oncallListenAlertTaskDo) CreateInBatches(values []*model.OncallListenAlertTask, batchSize int) error {
	return o.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (o oncallListenAlertTaskDo) Save(values ...*model.OncallListenAlertTask) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Save(values)
}

func (o oncallListenAlertTaskDo) First() (*model.OncallListenAlertTask, error) {
	if result, err := o.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.OncallListenAlertTask), nil
	}
}

func (o oncallListenAlertTaskDo) Take() (*model.OncallListenAlertTask, error) {
	if result, err := o.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.OncallListenAlertTask), nil
	}
}

func (o oncallListenAlertTaskDo) Last() (*model.OncallListenAlertTask, error) {
	if result, err := o.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.OncallListenAlertTask), nil
	}
}

func (o oncallListenAlertTaskDo) Find() ([]*model.OncallListenAlertTask, error) {
	result, err := o.DO.Find()
	return result.([]*model.OncallListenAlertTask), err
}

func (o oncallListenAlertTaskDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.OncallListenAlertTask, err error) {
	buf := make([]*model.OncallListenAlertTask, 0, batchSize)
	err = o.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (o oncallListenAlertTaskDo) FindInBatches(result *[]*model.OncallListenAlertTask, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return o.DO.FindInBatches(result, batchSize, fc)
}

func (o oncallListenAlertTaskDo) Attrs(attrs ...field.AssignExpr) *oncallListenAlertTaskDo {
	return o.withDO(o.DO.Attrs(attrs...))
}

func (o oncallListenAlertTaskDo) Assign(attrs ...field.AssignExpr) *oncallListenAlertTaskDo {
	return o.withDO(o.DO.Assign(attrs...))
}

func (o oncallListenAlertTaskDo) Joins(fields ...field.RelationField) *oncallListenAlertTaskDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Joins(_f))
	}
	return &o
}

func (o oncallListenAlertTaskDo) Preload(fields ...field.RelationField) *oncallListenAlertTaskDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Preload(_f))
	}
	return &o
}

func (o oncallListenAlertTaskDo) FirstOrInit() (*model.OncallListenAlertTask, error) {
	if result, err := o.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.OncallListenAlertTask), nil
	}
}

func (o oncallListenAlertTaskDo) FirstOrCreate() (*model.OncallListenAlertTask, error) {
	if result, err := o.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.OncallListenAlertTask), nil
	}
}

func (o oncallListenAlertTaskDo) FindByPage(offset int, limit int) (result []*model.OncallListenAlertTask, count int64, err error) {
	result, err = o.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = o.Offset(-1).Limit(-1).Count()
	return
}

func (o oncallListenAlertTaskDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = o.Count()
	if err != nil {
		return
	}

	err = o.Offset(offset).Limit(limit).Scan(result)
	return
}

func (o oncallListenAlertTaskDo) Scan(result interface{}) (err error) {
	return o.DO.Scan(result)
}

func (o oncallListenAlertTaskDo) Delete(models ...*model.OncallListenAlertTask) (result gen.ResultInfo, err error) {
	return o.DO.Delete(models)
}

func (o *oncallListenAlertTaskDo) withDO(do gen.Dao) *oncallListenAlertTaskDo {
	o.DO = *do.(*gen.DO)
	return o
}
