// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gen/helper"

	"gorm.io/plugin/dbresolver"

	"code.byted.org/oec/oncall_opinion_analyse/biz/dal/model"
)

func newOncallOriginRecord(db *gorm.DB) oncallOriginRecord {
	_oncallOriginRecord := oncallOriginRecord{}

	_oncallOriginRecord.oncallOriginRecordDo.UseDB(db)
	_oncallOriginRecord.oncallOriginRecordDo.UseModel(&model.OncallOriginRecord{})

	tableName := _oncallOriginRecord.oncallOriginRecordDo.TableName()
	_oncallOriginRecord.ALL = field.NewAsterisk(tableName)
	_oncallOriginRecord.ID = field.NewInt64(tableName, "id")
	_oncallOriginRecord.OncallOriginID = field.NewInt64(tableName, "oncall_origin_id")
	_oncallOriginRecord.TenantID = field.NewInt64(tableName, "tenant_id")
	_oncallOriginRecord.TenantName = field.NewString(tableName, "tenant_name")
	_oncallOriginRecord.Name = field.NewString(tableName, "name")
	_oncallOriginRecord.Level = field.NewString(tableName, "level")
	_oncallOriginRecord.Stage = field.NewString(tableName, "stage")
	_oncallOriginRecord.IsCrossTenant = field.NewBool(tableName, "is_cross_tenant")
	_oncallOriginRecord.CrossTenantID = field.NewInt64(tableName, "cross_tenant_id")
	_oncallOriginRecord.CrossTenantName = field.NewString(tableName, "cross_tenant_name")
	_oncallOriginRecord.CrossOncallFlowID = field.NewInt64(tableName, "cross_oncall_flow_id")
	_oncallOriginRecord.OriginatorUser = field.NewString(tableName, "originator_user")
	_oncallOriginRecord.HandlerUser = field.NewString(tableName, "handler_user")
	_oncallOriginRecord.CreateTime = field.NewTime(tableName, "create_time")
	_oncallOriginRecord.UpdateTime = field.NewTime(tableName, "update_time")
	_oncallOriginRecord.IsSolved = field.NewBool(tableName, "is_solved")
	_oncallOriginRecord.SolveTime = field.NewTime(tableName, "solve_time")
	_oncallOriginRecord.FeedbackContent = field.NewString(tableName, "feedback_content")
	_oncallOriginRecord.FeedbackScore = field.NewInt64(tableName, "feedback_score")
	_oncallOriginRecord.FeedbackTime = field.NewTime(tableName, "feedback_time")
	_oncallOriginRecord.OncallStartTime = field.NewTime(tableName, "oncall_start_time")
	_oncallOriginRecord.OncallEndTime = field.NewTime(tableName, "oncall_end_time")
	_oncallOriginRecord.DetailURL = field.NewString(tableName, "detail_url")
	_oncallOriginRecord.SourceLocation = field.NewString(tableName, "source_location")
	_oncallOriginRecord.IsNewer = field.NewBool(tableName, "is_newer")
	_oncallOriginRecord.OncallChatID = field.NewInt64(tableName, "oncall_chat_id")
	_oncallOriginRecord.ChatID = field.NewInt64(tableName, "chat_id")
	_oncallOriginRecord.SolveUser = field.NewString(tableName, "solve_user")
	_oncallOriginRecord.MessageLogs = field.NewString(tableName, "message_logs")
	_oncallOriginRecord.OriginatorCountry = field.NewString(tableName, "originator_country")
	_oncallOriginRecord.CTime = field.NewTime(tableName, "c_time")
	_oncallOriginRecord.UTime = field.NewTime(tableName, "u_time")
	_oncallOriginRecord.OncallResponseTime = field.NewTime(tableName, "oncall_response_time")

	_oncallOriginRecord.fillFieldMap()

	return _oncallOriginRecord
}

type oncallOriginRecord struct {
	oncallOriginRecordDo oncallOriginRecordDo

	ALL                field.Asterisk
	ID                 field.Int64  // 主键id
	OncallOriginID     field.Int64  // oncall工单主键id
	TenantID           field.Int64  // 租户主键
	TenantName         field.String // 租户名称
	Name               field.String // 流程名字，一般是问题描述
	Level              field.String // 级别
	Stage              field.String // 流程阶段
	IsCrossTenant      field.Bool   // 是否跨租户
	CrossTenantID      field.Int64  // 原Oncall工单租户主键
	CrossTenantName    field.String // 原Oncall工单租户名称
	CrossOncallFlowID  field.Int64  // 原Oncall工单流程主键
	OriginatorUser     field.String // 发起人
	HandlerUser        field.String // oncall 处理人
	CreateTime         field.Time   // 工单创建时间
	UpdateTime         field.Time   // 工单更新时间
	IsSolved           field.Bool   // 是否已解决
	SolveTime          field.Time   // 工单解决时间
	FeedbackContent    field.String // 反馈内容
	FeedbackScore      field.Int64  // 反馈分数
	FeedbackTime       field.Time   // 工单反馈时间
	OncallStartTime    field.Time   // oncall开始时间
	OncallEndTime      field.Time   // oncall结束时间
	DetailURL          field.String // 反馈平台的详情地址
	SourceLocation     field.String // 来源详情地址
	IsNewer            field.Bool   // 发起人是否是新人（入职两个月以内）
	OncallChatID       field.Int64  // oncall_chat 主键
	ChatID             field.Int64  // lark chat id
	SolveUser          field.String // 解决的用户邮箱前缀
	MessageLogs        field.String // 聊天记录
	OriginatorCountry  field.String // 发起人国家
	CTime              field.Time   // callback落库时间
	UTime              field.Time   // callback修改时间
	OncallResponseTime field.Time   // 响应时间

	fieldMap map[string]field.Expr
}

func (o oncallOriginRecord) Table(newTableName string) *oncallOriginRecord {
	o.oncallOriginRecordDo.UseTable(newTableName)
	return o.updateTableName(newTableName)
}

func (o oncallOriginRecord) As(alias string) *oncallOriginRecord {
	o.oncallOriginRecordDo.DO = *(o.oncallOriginRecordDo.As(alias).(*gen.DO))
	return o.updateTableName(alias)
}

func (o *oncallOriginRecord) updateTableName(table string) *oncallOriginRecord {
	o.ALL = field.NewAsterisk(table)
	o.ID = field.NewInt64(table, "id")
	o.OncallOriginID = field.NewInt64(table, "oncall_origin_id")
	o.TenantID = field.NewInt64(table, "tenant_id")
	o.TenantName = field.NewString(table, "tenant_name")
	o.Name = field.NewString(table, "name")
	o.Level = field.NewString(table, "level")
	o.Stage = field.NewString(table, "stage")
	o.IsCrossTenant = field.NewBool(table, "is_cross_tenant")
	o.CrossTenantID = field.NewInt64(table, "cross_tenant_id")
	o.CrossTenantName = field.NewString(table, "cross_tenant_name")
	o.CrossOncallFlowID = field.NewInt64(table, "cross_oncall_flow_id")
	o.OriginatorUser = field.NewString(table, "originator_user")
	o.HandlerUser = field.NewString(table, "handler_user")
	o.CreateTime = field.NewTime(table, "create_time")
	o.UpdateTime = field.NewTime(table, "update_time")
	o.IsSolved = field.NewBool(table, "is_solved")
	o.SolveTime = field.NewTime(table, "solve_time")
	o.FeedbackContent = field.NewString(table, "feedback_content")
	o.FeedbackScore = field.NewInt64(table, "feedback_score")
	o.FeedbackTime = field.NewTime(table, "feedback_time")
	o.OncallStartTime = field.NewTime(table, "oncall_start_time")
	o.OncallEndTime = field.NewTime(table, "oncall_end_time")
	o.DetailURL = field.NewString(table, "detail_url")
	o.SourceLocation = field.NewString(table, "source_location")
	o.IsNewer = field.NewBool(table, "is_newer")
	o.OncallChatID = field.NewInt64(table, "oncall_chat_id")
	o.ChatID = field.NewInt64(table, "chat_id")
	o.SolveUser = field.NewString(table, "solve_user")
	o.MessageLogs = field.NewString(table, "message_logs")
	o.OriginatorCountry = field.NewString(table, "originator_country")
	o.CTime = field.NewTime(table, "c_time")
	o.UTime = field.NewTime(table, "u_time")
	o.OncallResponseTime = field.NewTime(table, "oncall_response_time")

	o.fillFieldMap()

	return o
}

func (o *oncallOriginRecord) WithContext(ctx context.Context) *oncallOriginRecordDo {
	return o.oncallOriginRecordDo.WithContext(ctx)
}

func (o oncallOriginRecord) TableName() string { return o.oncallOriginRecordDo.TableName() }

func (o oncallOriginRecord) Alias() string { return o.oncallOriginRecordDo.Alias() }

func (o *oncallOriginRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := o.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (o *oncallOriginRecord) fillFieldMap() {
	o.fieldMap = make(map[string]field.Expr, 33)
	o.fieldMap["id"] = o.ID
	o.fieldMap["oncall_origin_id"] = o.OncallOriginID
	o.fieldMap["tenant_id"] = o.TenantID
	o.fieldMap["tenant_name"] = o.TenantName
	o.fieldMap["name"] = o.Name
	o.fieldMap["level"] = o.Level
	o.fieldMap["stage"] = o.Stage
	o.fieldMap["is_cross_tenant"] = o.IsCrossTenant
	o.fieldMap["cross_tenant_id"] = o.CrossTenantID
	o.fieldMap["cross_tenant_name"] = o.CrossTenantName
	o.fieldMap["cross_oncall_flow_id"] = o.CrossOncallFlowID
	o.fieldMap["originator_user"] = o.OriginatorUser
	o.fieldMap["handler_user"] = o.HandlerUser
	o.fieldMap["create_time"] = o.CreateTime
	o.fieldMap["update_time"] = o.UpdateTime
	o.fieldMap["is_solved"] = o.IsSolved
	o.fieldMap["solve_time"] = o.SolveTime
	o.fieldMap["feedback_content"] = o.FeedbackContent
	o.fieldMap["feedback_score"] = o.FeedbackScore
	o.fieldMap["feedback_time"] = o.FeedbackTime
	o.fieldMap["oncall_start_time"] = o.OncallStartTime
	o.fieldMap["oncall_end_time"] = o.OncallEndTime
	o.fieldMap["detail_url"] = o.DetailURL
	o.fieldMap["source_location"] = o.SourceLocation
	o.fieldMap["is_newer"] = o.IsNewer
	o.fieldMap["oncall_chat_id"] = o.OncallChatID
	o.fieldMap["chat_id"] = o.ChatID
	o.fieldMap["solve_user"] = o.SolveUser
	o.fieldMap["message_logs"] = o.MessageLogs
	o.fieldMap["originator_country"] = o.OriginatorCountry
	o.fieldMap["c_time"] = o.CTime
	o.fieldMap["u_time"] = o.UTime
	o.fieldMap["oncall_response_time"] = o.OncallResponseTime
}

func (o oncallOriginRecord) clone(db *gorm.DB) oncallOriginRecord {
	o.oncallOriginRecordDo.ReplaceDB(db)
	return o
}

type oncallOriginRecordDo struct{ gen.DO }

// select * from @@table
// {{where}}
//
//	is_solved = 0 and
//	level = @level and
//	oncall_response_time is true and
//	TIMESTAMPDIFF(MINUTE,create_time,oncall_response_time) > @allowedMinuteTime and
//
// create_time >= @startTime
// {{end}}
func (o oncallOriginRecordDo) FindNotSolveAndResponseTimeNotAllowed(level string, allowedMinuteTime int64, startTime string) (result []*model.OncallOriginRecord, err error) {
	params := make(map[string]interface{}, 0)

	var generateSQL strings.Builder
	generateSQL.WriteString("select * from oncall_origin_record ")
	var whereSQL0 strings.Builder
	params["level"] = level
	params["allowedMinuteTime"] = allowedMinuteTime
	params["startTime"] = startTime
	whereSQL0.WriteString("is_solved = 0 and level = @level and oncall_response_time is true and TIMESTAMPDIFF(MINUTE,create_time,oncall_response_time) > @allowedMinuteTime and create_time >= @startTime ")
	helper.JoinWhereBuilder(&generateSQL, whereSQL0)

	var executeSQL *gorm.DB
	if len(params) > 0 {
		executeSQL = o.UnderlyingDB().Raw(generateSQL.String(), params).Find(&result)
	} else {
		executeSQL = o.UnderlyingDB().Raw(generateSQL.String()).Find(&result)
	}
	err = executeSQL.Error
	return
}

// select * from @@table
// {{where}}
//
//	is_solved = 0 and
//	level = @level and
//	oncall_response_time is NULL and
//	TIMESTAMPDIFF(MINUTE,create_time,Now()) > @allowedMinuteTime and
//
// create_time >= @startTime
// {{end}}
func (o oncallOriginRecordDo) FindNotSolveAndNoResponseTimeNotAllowed(level string, allowedMinuteTime int64, startTime string) (result []*model.OncallOriginRecord, err error) {
	params := make(map[string]interface{}, 0)

	var generateSQL strings.Builder
	generateSQL.WriteString("select * from oncall_origin_record ")
	var whereSQL0 strings.Builder
	params["level"] = level
	params["allowedMinuteTime"] = allowedMinuteTime
	params["startTime"] = startTime
	whereSQL0.WriteString("is_solved = 0 and level = @level and oncall_response_time is NULL and TIMESTAMPDIFF(MINUTE,create_time,Now()) > @allowedMinuteTime and create_time >= @startTime ")
	helper.JoinWhereBuilder(&generateSQL, whereSQL0)

	var executeSQL *gorm.DB
	if len(params) > 0 {
		executeSQL = o.UnderlyingDB().Raw(generateSQL.String(), params).Find(&result)
	} else {
		executeSQL = o.UnderlyingDB().Raw(generateSQL.String()).Find(&result)
	}
	err = executeSQL.Error
	return
}

func (o oncallOriginRecordDo) Debug() *oncallOriginRecordDo {
	return o.withDO(o.DO.Debug())
}

func (o oncallOriginRecordDo) WithContext(ctx context.Context) *oncallOriginRecordDo {
	return o.withDO(o.DO.WithContext(ctx))
}

func (o oncallOriginRecordDo) ReadDB() *oncallOriginRecordDo {
	return o.Clauses(dbresolver.Read)
}

func (o oncallOriginRecordDo) WriteDB() *oncallOriginRecordDo {
	return o.Clauses(dbresolver.Write)
}

func (o oncallOriginRecordDo) Clauses(conds ...clause.Expression) *oncallOriginRecordDo {
	return o.withDO(o.DO.Clauses(conds...))
}

func (o oncallOriginRecordDo) Returning(value interface{}, columns ...string) *oncallOriginRecordDo {
	return o.withDO(o.DO.Returning(value, columns...))
}

func (o oncallOriginRecordDo) Not(conds ...gen.Condition) *oncallOriginRecordDo {
	return o.withDO(o.DO.Not(conds...))
}

func (o oncallOriginRecordDo) Or(conds ...gen.Condition) *oncallOriginRecordDo {
	return o.withDO(o.DO.Or(conds...))
}

func (o oncallOriginRecordDo) Select(conds ...field.Expr) *oncallOriginRecordDo {
	return o.withDO(o.DO.Select(conds...))
}

func (o oncallOriginRecordDo) Where(conds ...gen.Condition) *oncallOriginRecordDo {
	return o.withDO(o.DO.Where(conds...))
}

func (o oncallOriginRecordDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *oncallOriginRecordDo {
	return o.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (o oncallOriginRecordDo) Order(conds ...field.Expr) *oncallOriginRecordDo {
	return o.withDO(o.DO.Order(conds...))
}

func (o oncallOriginRecordDo) Distinct(cols ...field.Expr) *oncallOriginRecordDo {
	return o.withDO(o.DO.Distinct(cols...))
}

func (o oncallOriginRecordDo) Omit(cols ...field.Expr) *oncallOriginRecordDo {
	return o.withDO(o.DO.Omit(cols...))
}

func (o oncallOriginRecordDo) Join(table schema.Tabler, on ...field.Expr) *oncallOriginRecordDo {
	return o.withDO(o.DO.Join(table, on...))
}

func (o oncallOriginRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) *oncallOriginRecordDo {
	return o.withDO(o.DO.LeftJoin(table, on...))
}

func (o oncallOriginRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) *oncallOriginRecordDo {
	return o.withDO(o.DO.RightJoin(table, on...))
}

func (o oncallOriginRecordDo) Group(cols ...field.Expr) *oncallOriginRecordDo {
	return o.withDO(o.DO.Group(cols...))
}

func (o oncallOriginRecordDo) Having(conds ...gen.Condition) *oncallOriginRecordDo {
	return o.withDO(o.DO.Having(conds...))
}

func (o oncallOriginRecordDo) Limit(limit int) *oncallOriginRecordDo {
	return o.withDO(o.DO.Limit(limit))
}

func (o oncallOriginRecordDo) Offset(offset int) *oncallOriginRecordDo {
	return o.withDO(o.DO.Offset(offset))
}

func (o oncallOriginRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *oncallOriginRecordDo {
	return o.withDO(o.DO.Scopes(funcs...))
}

func (o oncallOriginRecordDo) Unscoped() *oncallOriginRecordDo {
	return o.withDO(o.DO.Unscoped())
}

func (o oncallOriginRecordDo) Create(values ...*model.OncallOriginRecord) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Create(values)
}

func (o oncallOriginRecordDo) CreateInBatches(values []*model.OncallOriginRecord, batchSize int) error {
	return o.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (o oncallOriginRecordDo) Save(values ...*model.OncallOriginRecord) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Save(values)
}

func (o oncallOriginRecordDo) First() (*model.OncallOriginRecord, error) {
	if result, err := o.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.OncallOriginRecord), nil
	}
}

func (o oncallOriginRecordDo) Take() (*model.OncallOriginRecord, error) {
	if result, err := o.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.OncallOriginRecord), nil
	}
}

func (o oncallOriginRecordDo) Last() (*model.OncallOriginRecord, error) {
	if result, err := o.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.OncallOriginRecord), nil
	}
}

func (o oncallOriginRecordDo) Find() ([]*model.OncallOriginRecord, error) {
	result, err := o.DO.Find()
	return result.([]*model.OncallOriginRecord), err
}

func (o oncallOriginRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.OncallOriginRecord, err error) {
	buf := make([]*model.OncallOriginRecord, 0, batchSize)
	err = o.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (o oncallOriginRecordDo) FindInBatches(result *[]*model.OncallOriginRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return o.DO.FindInBatches(result, batchSize, fc)
}

func (o oncallOriginRecordDo) Attrs(attrs ...field.AssignExpr) *oncallOriginRecordDo {
	return o.withDO(o.DO.Attrs(attrs...))
}

func (o oncallOriginRecordDo) Assign(attrs ...field.AssignExpr) *oncallOriginRecordDo {
	return o.withDO(o.DO.Assign(attrs...))
}

func (o oncallOriginRecordDo) Joins(fields ...field.RelationField) *oncallOriginRecordDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Joins(_f))
	}
	return &o
}

func (o oncallOriginRecordDo) Preload(fields ...field.RelationField) *oncallOriginRecordDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Preload(_f))
	}
	return &o
}

func (o oncallOriginRecordDo) FirstOrInit() (*model.OncallOriginRecord, error) {
	if result, err := o.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.OncallOriginRecord), nil
	}
}

func (o oncallOriginRecordDo) FirstOrCreate() (*model.OncallOriginRecord, error) {
	if result, err := o.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.OncallOriginRecord), nil
	}
}

func (o oncallOriginRecordDo) FindByPage(offset int, limit int) (result []*model.OncallOriginRecord, count int64, err error) {
	result, err = o.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = o.Offset(-1).Limit(-1).Count()
	return
}

func (o oncallOriginRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = o.Count()
	if err != nil {
		return
	}

	err = o.Offset(offset).Limit(limit).Scan(result)
	return
}

func (o oncallOriginRecordDo) Scan(result interface{}) (err error) {
	return o.DO.Scan(result)
}

func (o oncallOriginRecordDo) Delete(models ...*model.OncallOriginRecord) (result gen.ResultInfo, err error) {
	return o.DO.Delete(models)
}

func (o *oncallOriginRecordDo) withDO(do gen.Dao) *oncallOriginRecordDo {
	o.DO = *do.(*gen.DO)
	return o
}
