// Code generated by hertztool.

package handler

import (
	"context"
	"strings"

	"github.com/bytedance/sonic"

	"code.byted.org/gopkg/env"
	"code.byted.org/gopkg/logs/v2/log"
	"code.byted.org/middleware/hertz/pkg/app"
	"code.byted.org/middleware/hertz_ext/v2/binding"
	"code.byted.org/oec/oncall_opinion_analyse/biz/model"
	"code.byted.org/oec/rpcv2_oec_security_dispose_center/rpc/oec_security_dispose_center"
)

type MockSentryDetail struct {
	ActionPackage   string   `json:"action_package"` // 指定动作包调用
	FactorList      []string `json:"factor_list"`    //指定因子调用
	EventCode       string   `json:"event_code"`
	IgnoreExemption bool     `json:"ignore_exemption"`
	SceneCode       string   `json:"scene_code"`
	ExemptDuration  int32    `json:"exempt_duration"` // 豁免时长,单位s
	Exclude         []string `json:"exclude"`         // 需排除的因子（如本次登录方式）
	Content         string   `json:"content"`         // http resp返回的内容
}

// AutoTestIdv .
// @router /osgw_v2/autotest/idv [Any]
func AutoTestIdv(ctx context.Context, c *app.RequestContext) { // ignore_security_alert
	var err error
	var req model.IDVMockRequest
	var factorList []string
	err = binding.BindAndValidate(c, &req)
	if req.FactorList != "" {
		factorList = strings.Split(req.FactorList, ",")
	}
	if err != nil {
		c.String(400, err.Error())
		return
	}
	detail, _ := sonic.MarshalString(map[string]interface{}{
		"from":      "sentry",
		"operation": "idv",
		"version":   "1.0.0",
		"detail": &MockSentryDetail{
			ActionPackage:   req.ActionPackage,
			FactorList:      factorList,
			EventCode:       req.EventCode,
			IgnoreExemption: req.IgnoreExemption,
			SceneCode:       req.SceneCode,
			ExemptDuration:  req.ExemptDuration,
			Exclude:         strings.Split(req.Exclude, ","),
			Content:         req.Content,
		}})

	params := make(map[string]string)
	c.VisitAllQueryArgs(func(key, value []byte) {
		k, v := string(key), string(value)
		switch k {
		case "u_zhouli_id":
			params["user_id"] = v
		case "app_id":
			params["app_id"] = v
		default:
			params[k] = v
		}
	})
	params["psm"] = env.PSM()
	params["path"] = "/osgw_v2/autotest/idv"
	params["oec_vc_sdk_version"] = string(c.GetHeader("oec-vc-sdk-version"))
	disposeResp, err := oec_security_dispose_center.DisposeV2(ctx, "sentry", detail, params)
	if err != nil {
		c.String(200, err.Error())
		return
	}
	if disposeResp.IsSetResponse() {
		httpResp := disposeResp.GetResponse()
		resp, _ := sonic.MarshalString(httpResp)
		log.V1.CtxInfo(ctx, "http resp:%v", resp)
		for _, h := range httpResp.GetHeaders() {
			//log.V1.CtxInfo(ctx, "add header key:%v, value:%v", h.GetKey(), h.GetValue())
			c.Header(h.GetKey(), h.GetValue())
		}
		switch env.GetCurrentVRegion() {
		case env.VREGION_USTTP, env.VREGION_USTTP2, env.VREGION_EUTTP2, env.VREGION_USEASTRED:
			c.String(int(httpResp.GetStatusCode()), "{}") // 避免og拦截
		default:
			c.String(int(httpResp.GetStatusCode()), string(httpResp.GetBody()))
		}
		return
	}

	//switch env.GetCurrentVRegion() {
	//case env.VREGION_USTTP, env.VREGION_USTTP2, env.VREGION_EUTTP2, env.VREGION_USEASTRED:
	//	c.String(200, "this is a normal response{}")
	//default:
	//	c.String(200, `{"msg":"this is a normal response"}`)
	//}

}
