// Code generated by hertztool.

package handler

import (
	"code.byted.org/gopkg/logs"
	"code.byted.org/middleware/hertz/pkg/app"
	"code.byted.org/middleware/hertz_ext/v2/binding"
	"code.byted.org/oec/oncall_opinion_analyse/biz/model/governance_qa_serv"
	"code.byted.org/oec/oncall_opinion_analyse/biz/service"
	"context"
)

// GetOncallArgosDIYCardCallback .
// @router /api/v:version/oec/governance/qa/argos/callback [POST]
func GetOncallArgosDIYCardCallback(ctx context.Context, c *app.RequestContext) {
	var err error
	var req governance_qa_serv.ArgosTagValsCallBackRequest
	err = binding.BindAndValidate(c, &req)
	if err != nil {
		c.String(400, err.Error())
		return
	}
	logs.CtxInfo(ctx, "GetOncallArgosDIYCardCallback request: {%s}", req.String())
	resp := service.BuildDIYArgosCard(ctx, &req)
	err = binding.WriteHeader(c, resp)
	if err != nil {
		c.String(500, err.Error())
		return
	}
	logs.CtxInfo(ctx, "GetOncallArgosDIYCardCallback response: {%s}", resp.String())
	c.JSON(200, resp)
}
