// Code generated by hertztool.

package handler

import (
	"code.byted.org/gopkg/logs"
	"code.byted.org/middleware/hertz/pkg/app"
	"code.byted.org/middleware/hertz_ext/v2/binding"
	"code.byted.org/oec/oncall_opinion_analyse/biz/dal/model"
	"code.byted.org/oec/oncall_opinion_analyse/biz/dal/query"
	"code.byted.org/oec/oncall_opinion_analyse/biz/model/governance_qa_serv"
	"code.byted.org/oec/oncall_opinion_analyse/biz/service"
	"code.byted.org/oec/oncall_opinion_analyse/biz/util/common"
	"code.byted.org/oec/status_code/Status"
	"context"
	"encoding/json"
	"errors"
	"google.golang.org/protobuf/proto"
	"net/http"
	"strconv"
)

// GetOncallCallback .
// @router /api/v:version/oec/oncall/workorder/callback [POST]
func GetOncallCallback(ctx context.Context, c *app.RequestContext) {
	var err error
	var req governance_qa_serv.OncallWorkOrderCallbackRequest
	err = binding.BindAndValidate(c, &req)
	if err != nil {
		logs.CtxError(ctx, "GetOncallCallback MakeErrorResponse: code: %d, msg: %s.", 400, err.Error())
		c.String(400, err.Error())
		return
	}
	logs.CtxInfo(ctx, "GetOncallCallback request: {%s}", req.String())
	// 保存oncall原始工单记录
	//err = saveOncallWorkFlow(ctx, req.GetOncallFlow())
	//if err != nil {
	//	logs.CtxInfo(ctx, "InsertDBErrorResponse: code: %d, msg: %s.", 500, err.Error())
	//	c.String(500, err.Error())
	//	return
	//}
	//// 创建告警任务，并进行日志打点
	//// ToDo：需要异步化因为要调用算法服务耗时较长
	//err = saveAlertTask(ctx, req.GetOncallFlow(), req.GetAction())
	//if err != nil {
	//	logs.CtxError(ctx, "InsertDBErrorResponse: code: %d, msg: %s.", 500, err.Error())
	//	c.String(500, err.Error())
	//	return
	//}
	resp := new(governance_qa_serv.OncallWorkOrderCallbackResponse)
	err = binding.WriteHeader(c, resp)
	if err != nil {
		logs.CtxInfo(ctx, "MakeErrorResponse: code: %d, msg: %s.", 500, err.Error())
		c.String(500, err.Error())
		return
	}
	logs.CtxInfo(ctx, "MakeSuccessResponse: req success.")
	resp.Code = proto.Int32(Status.Success.Code())
	resp.Message = proto.String(Status.Success.StarlingText(""))
	c.JSON(http.StatusOK, resp)
}
func saveOncallWorkFlow(ctx context.Context, originalRecord *governance_qa_serv.OncallFlow) error {
	if originalRecord == nil {
		logs.CtxError(ctx, "request empty originalRecord.[%s]", originalRecord)
		return errors.New("empty originalRecord")
	}
	data, err := common.CopyOriginalOncallRecord(originalRecord)
	if err != nil || data == nil {
		logs.CtxError(ctx, "format json to struct err! plz check ctx, error detail:%v", err.Error())
		return err
	}
	// if no source location, we contact url under this rule
	//if data.SourceLocation == nil || *data.SourceLocation == "source_location" || !common.IsValidUrl(*data.SourceLocation) {
	//	data.SourceLocation = proto.String("https://oncall.bytedance.net/admin/review/all?id=" + strconv.FormatInt(originalRecord.GetId(), 10) + "&picked_detail=" + strconv.FormatInt(originalRecord.GetId(), 10))
	//}
	data.SourceLocation = proto.String("https://oncall.bytedance.net/admin/review/all?id=" + strconv.FormatInt(originalRecord.GetId(), 10) + "&picked_detail=" + strconv.FormatInt(originalRecord.GetId(), 10))
	q := query.Use(query.WriteDB(ctx))
	oor := q.OncallOriginRecord.WithContext(ctx)
	err = oor.Save(data)
	if err != nil {
		logs.CtxError(ctx, "create oncall record data error. plz check rds or insert data: %v", err.Error())
		return err
	}
	return nil
}

func saveAlertTask(ctx context.Context, originalRecord *governance_qa_serv.OncallFlow, action string) error {

	if originalRecord.GetStage() == "not_start" {
		return nil
	}

	var task *model.OncallListenAlertTask
	task = new(model.OncallListenAlertTask)

	task.OncallOriginID = originalRecord.Id
	task.TenantID = *originalRecord.TenantId
	task.CreateTime = originalRecord.CreateTime
	task.UpdateTime = originalRecord.UpdateTime
	task.MatchKeywords = new(string)
	task.ClusterTags = new(string)
	task.CalculatedAlertLevel = new(string)
	task.ActualAlertLevel = new(string)

	var status int32
	switch action {
	case "init":
		status = int32(0)
	case "solve_flow":
		status = int32(99)
	default:
		status = int32(1)
	}
	task.Status = &status

	// log listen for argos alter
	service.GenArgosAlertData(ctx, originalRecord, task)
	js, ee := json.Marshal(task)
	if ee == nil {
		ss := string(js)
		logs.CtxInfo(ctx, "save alert task into db if needed: %s", ss)
	} else {
		logs.CtxInfo(ctx, "save alert task into db if needed, but parsed task to json err:%v", ee.Error())
	}

	// save alert task into db
	q := query.Use(query.WriteDB(ctx))
	oor := q.OncallListenAlertTask.WithContext(ctx)
	e := oor.Save(task)
	if e != nil {
		logs.CtxError(ctx, "create alert task data error. plz check rds or insert data: %v", e.Error())
		return e
	}
	return nil
}

func getAlertTask(ctx context.Context, originalRecord *governance_qa_serv.OncallFlow) (*model.OncallListenAlertTask, error) {
	q := query.Use(query.ReadDB(ctx))
	var task *model.OncallListenAlertTask
	var err error
	r := q.OncallListenAlertTask.WithContext(ctx)
	task, err = r.Where(q.OncallListenAlertTask.OncallOriginID.Eq(*originalRecord.Id)).Take()
	if err != nil {
		logs.CtxInfo(ctx, "not found in alert task table")
		return nil, err
	}
	return task, nil
}
