// This file is automatically generated. Do not modify.

package model

import (
	"fmt"
)

var _ = fmt.Sprintf

type EmptyReq struct {
}

type EmptyResp struct {
}

type IDVMockRequest struct {
	ActionPackage   string `json:"actionPackage" query:"action_package"`
	EventCode       string `json:"eventCode" query:"event_code"`
	IgnoreExemption bool   `json:"ignoreExemption" query:"ignore_exemption"`
	FactorList      string `json:"factorList" query:"factor_list"`
	SceneCode       string `json:"sceneCode" query:"scene_code"`
	ExemptDuration  int32  `json:"exemptDuration" query:"exempt_duration"`
	Exclude         string `json:"exclude" query:"exclude"`
	Content         string `json:"content" query:"content"`
	AppVersion      string `json:"app_version" query:"app_version"`
	SdkVersion      string `json:"sdk_version" query:"sdk_version"`
}

type IDVMockResp struct {
	Code int32  `form:"code" json:"code" query:"code"`
	Msg  string `form:"msg" json:"msg" query:"msg"`
}
