// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAlertTask = "alert_task"

// AlertTask mapped from table <alert_task>
type AlertTask struct {
	ID                int64     `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`        // 主键id
	OncallOriginID    *int64    `gorm:"column:oncall_origin_id;type:bigint" json:"oncall_origin_id"`                   // 原始oncall工单主键id
	TenantID          int64     `gorm:"column:tenant_id;type:bigint;not null" json:"tenant_id"`                        // 租户主键
	AlterType         *string   `gorm:"column:alter_type;type:varchar(64)" json:"alter_type"`                          // 该条工单告警类别
	CTime             time.Time `gorm:"column:c_time;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"c_time"` // 落库时间
	UTime             time.Time `gorm:"column:u_time;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"u_time"` // 修改时间
	Level             *string   `gorm:"column:level;type:varchar(20)" json:"level"`                                    // 告警等级
	IsCallback        int32     `gorm:"column:is_callback;type:int;not null" json:"is_callback"`                       // 是否被argos告警callback过
	CrossOncallFlowID *int64    `gorm:"column:cross_oncall_flow_id;type:bigint" json:"cross_oncall_flow_id"`           // 同流程内oncall工单关联id
	RootField         *string   `gorm:"column:root_field;type:varchar(10)" json:"root_field"`                          // oncall id 租户所属业务域
}

// TableName AlertTask's table name
func (*AlertTask) TableName() string {
	return TableNameAlertTask
}
