// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOncallListenAlertTask = "oncall_listen_alert_task"

// OncallListenAlertTask mapped from table <oncall_listen_alert_task>
type OncallListenAlertTask struct {
	ID                   int64     `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`                                   // 主键id
	OncallOriginID       *int64    `gorm:"column:oncall_origin_id;type:bigint;uniqueIndex:uniq_oncall_origin_id,priority:1" json:"oncall_origin_id"` // 原始oncall工单主键id
	TenantID             int64     `gorm:"column:tenant_id;type:bigint;not null" json:"tenant_id"`                                                   // 租户主键
	ActualAlertLevel     *string   `gorm:"column:actual_alert_level;type:varchar(20)" json:"actual_alert_level"`                                     // 该条工单实际告警级别
	CalculatedAlertLevel *string   `gorm:"column:calculated_alert_level;type:varchar(20)" json:"calculated_alert_level"`                             // 该条工单告警计算级别
	MatchKeywords        *string   `gorm:"column:match_keywords;type:text" json:"match_keywords"`                                                    // 工单命中关键词列表，包括匹配个数，目前默认为1个,ex:[{"kw1":1},...]
	ClusterTags          *string   `gorm:"column:cluster_tags;type:text" json:"cluster_tags"`                                                        // 工单聚合问题标签分类列表,ex:["tag1",...]
	Status               *int32    `gorm:"column:status;type:int" json:"status"`                                                                     // 状态,0:初始化，1:工单告警处理中，99:工单结束
	CreateTime           *string   `gorm:"column:create_time;type:varchar(20)" json:"create_time"`                                                   // 创建时间
	UpdateTime           *string   `gorm:"column:update_time;type:varchar(20)" json:"update_time"`                                                   // 修改时间
	CTime                time.Time `gorm:"column:c_time;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"c_time"`                            // callback落库时间
	UTime                time.Time `gorm:"column:u_time;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"u_time"`                            // callback修改时间
}

// TableName OncallListenAlertTask's table name
func (*OncallListenAlertTask) TableName() string {
	return TableNameOncallListenAlertTask
}
