// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOncallOriginRecord = "oncall_origin_record"

// OncallOriginRecord mapped from table <oncall_origin_record>
// 注意，自动生产的属性名的ID大小写与hertz的pb接口生成协议不一致，需要手动修改
type OncallOriginRecord struct {
	ID                 int64      `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`                                   // 主键id
	OncallOriginId     *int64     `gorm:"column:oncall_origin_id;type:bigint;uniqueIndex:uniq_oncall_origin_id,priority:1" json:"oncall_origin_id"` // oncall工单主键id
	TenantId           *int64     `gorm:"column:tenant_id;type:bigint" json:"tenant_id"`                                                            // 租户主键
	TenantName         *string    `gorm:"column:tenant_name;type:varchar(50)" json:"tenant_name"`                                                   // 租户名称
	Name               *string    `gorm:"column:name;type:varchar(1024)" json:"name"`                                                               // 流程名字，一般是问题描述
	Level              *string    `gorm:"column:level;type:varchar(20)" json:"level"`                                                               // 级别
	Stage              *string    `gorm:"column:stage;type:varchar(20)" json:"stage"`                                                               // 流程阶段
	IsCrossTenant      *bool      `gorm:"column:is_cross_tenant;type:tinyint(1)" json:"is_cross_tenant"`                                            // 是否跨租户
	CrossTenantId      *int64     `gorm:"column:cross_tenant_id;type:bigint" json:"cross_tenant_id"`                                                // 原Oncall工单租户主键
	CrossTenantName    *string    `gorm:"column:cross_tenant_name;type:varchar(50)" json:"cross_tenant_name"`                                       // 原Oncall工单租户名称
	CrossOncallFlowId  *int64     `gorm:"column:cross_oncall_flow_id;type:bigint" json:"cross_oncall_flow_id"`                                      // 原Oncall工单流程主键
	OriginatorUser     *string    `gorm:"column:originator_user;type:varchar(50)" json:"originator_user"`                                           // 发起人
	HandlerUser        *string    `gorm:"column:handler_user;type:varchar(50)" json:"handler_user"`                                                 // oncall 处理人
	CreateTime         *time.Time `gorm:"column:create_time;type:datetime" json:"create_time"`                                                      // 工单创建时间
	UpdateTime         *time.Time `gorm:"column:update_time;type:datetime" json:"update_time"`                                                      // 工单更新时间
	IsSolved           *bool      `gorm:"column:is_solved;type:tinyint(1)" json:"is_solved"`                                                        // 是否已解决
	SolveTime          *time.Time `gorm:"column:solve_time;type:datetime" json:"solve_time"`                                                        // 工单解决时间
	FeedbackContent    *string    `gorm:"column:feedback_content;type:varchar(1024)" json:"feedback_content"`                                       // 反馈内容
	FeedbackScore      *int64     `gorm:"column:feedback_score;type:bigint" json:"feedback_score"`                                                  // 反馈分数
	FeedbackTime       *time.Time `gorm:"column:feedback_time;type:datetime" json:"feedback_time"`                                                  // 工单反馈时间
	OncallStartTime    *time.Time `gorm:"column:oncall_start_time;type:datetime" json:"oncall_start_time"`                                          // oncall开始时间
	OncallEndTime      *time.Time `gorm:"column:oncall_end_time;type:datetime" json:"oncall_end_time"`                                              // oncall结束时间
	DetailURL          *string    `gorm:"column:detail_url;type:varchar(512)" json:"detail_url"`                                                    // 反馈平台的详情地址
	SourceLocation     *string    `gorm:"column:source_location;type:varchar(512)" json:"source_location"`                                          // 来源详情地址
	IsNewer            *bool      `gorm:"column:is_newer;type:tinyint(1)" json:"is_newer"`                                                          // 发起人是否是新人（入职两个月以内）
	OncallChatId       *int64     `gorm:"column:oncall_chat_id;type:bigint" json:"oncall_chat_id"`                                                  // oncall_chat 主键
	ChatId             *int64     `gorm:"column:chat_id;type:bigint" json:"chat_id"`                                                                // lark chat id
	SolveUser          *string    `gorm:"column:solve_user;type:varchar(20)" json:"solve_user"`                                                     // 解决的用户邮箱前缀
	MessageLogs        *string    `gorm:"column:message_logs;type:text" json:"message_logs"`                                                        // 聊天记录
	OriginatorCountry  *string    `gorm:"column:originator_country;type:varchar(20)" json:"originator_country"`                                     // 发起人国家
	CTime              time.Time  `gorm:"column:c_time;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"c_time"`                            // callback落库时间
	UTime              time.Time  `gorm:"column:u_time;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"u_time"`                            // callback修改时间
	OncallResponseTime *time.Time `gorm:"column:oncall_response_time;type:datetime" json:"oncall_response_time"`                                    // 响应时间
}

// TableName OncallOriginRecord's table name
func (*OncallOriginRecord) TableName() string {
	return TableNameOncallOriginRecord
}
